"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.typeDefinitions = void 0;
var apollo_server_express_1 = require("apollo-server-express");
var typeDefinitions = apollo_server_express_1.gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\ntype User {\n    id: ID!\n    name: String!\n    email: String!\n    links: [Link]!\n    collections: [Collection]!\n}\n\ntype Link {\n    annotation: String\n    tags: [String]\n    note: String\n    url: String!\n    owner: String!\n    id: ID!\n    createdAt: String!\n}\n\ntype Collection {\n    id: ID!\n    links: [Link]\n    name: String!\n    children: [Collection]\n    createdAt: String!\n    parent: String!\n    owner: String!\n}\n\n\ntype ActionStatus {\n    status: String\n}\n\ntype Query {\n    user: User\n    searchLinks(search: String!, type: String!): [Link]\n    hello: String!\n}\n\ntype Mutation {\n    createLink(annotation: String!, url: String!, tags: [String]!): ActionStatus\n    updateLink(linkId: String!, annotation: String, url: String, tags: [String], note: String): ActionStatus\n    deleteLink(linkId: String!): ActionStatus\n    createCollection(name: String!, parent: String): ActionStatus\n    updateCollection(collectionId: String!, name: String, tags: [String], links: [String]): ActionStatus\n    deleteCollection(collectionId: String!): ActionStatus\n    dropLink(collectionId: String!, linkId: String!): ActionStatus\n    removeLink(collectionId: String!, linkId: String!): ActionStatus\n}\n"], ["\n\ntype User {\n    id: ID!\n    name: String!\n    email: String!\n    links: [Link]!\n    collections: [Collection]!\n}\n\ntype Link {\n    annotation: String\n    tags: [String]\n    note: String\n    url: String!\n    owner: String!\n    id: ID!\n    createdAt: String!\n}\n\ntype Collection {\n    id: ID!\n    links: [Link]\n    name: String!\n    children: [Collection]\n    createdAt: String!\n    parent: String!\n    owner: String!\n}\n\n\ntype ActionStatus {\n    status: String\n}\n\ntype Query {\n    user: User\n    searchLinks(search: String!, type: String!): [Link]\n    hello: String!\n}\n\ntype Mutation {\n    createLink(annotation: String!, url: String!, tags: [String]!): ActionStatus\n    updateLink(linkId: String!, annotation: String, url: String, tags: [String], note: String): ActionStatus\n    deleteLink(linkId: String!): ActionStatus\n    createCollection(name: String!, parent: String): ActionStatus\n    updateCollection(collectionId: String!, name: String, tags: [String], links: [String]): ActionStatus\n    deleteCollection(collectionId: String!): ActionStatus\n    dropLink(collectionId: String!, linkId: String!): ActionStatus\n    removeLink(collectionId: String!, linkId: String!): ActionStatus\n}\n"])));
exports.typeDefinitions = typeDefinitions;
var templateObject_1;
