# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LinksBookv2 Server Build Test

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        run:
          working-directory: ${{ env.working-directory }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: tsc
